
name: fitbit-app
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: [3.6.14, 3.7]
    steps:
    - uses: actions/checkout@v2
    - name: ci_run
      env:
         repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        pip install -r requirements.txt
        python main.py
