
name: water-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: [3.6.14, 3.6.13, 3.7]
    steps:
    
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install all dependencies
      env:
         repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        pip install -r requirements.txt
        
    - name: Test application
      run: |
        python test.py
    
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:master -f
